# Test your FastAPI endpoints

GET http://127.0.0.1:58000/
Accept: application/json

###

GET http://127.0.0.1:58000/hello/User
Accept: application/json

###
POST http://127.0.0.1:58000/feishu_event
Accept: application/json
Content-Type: application/json; charset=utf-8
X-Lark-Request-Timestamp": "1692583523"
X-Lark-Signature: 53391afdc57aa41345305d4b829a99565e2661aca7a429545754646af005ace1
x-request-id: 0ebc528f-6955-4acf-895d-b367e2fd1358
{
    "challenge": "ajls384kdjx98XX",
    "token": "xxxxxx",
    "type": "url_verification"
}

### Fershu Encrpty
POST http://127.0.0.1:58000/feishu_event
Accept: application/json
Content-Type: application/json;charset=utf-8
x-lark-request-nonce: 801072633
x-lark-request-timestamp: 1692583523
x-lark-signature: 53391afdc57aa41345305d4b829a99565e2661aca7a429545754646af005ace1
x-request-id: 0ebc528f-6955-4acf-895d-b367e2fd1358

{"encrypt":"WXn42FbHLEwmjbeGNstrdRE4RVdRQ3h3EFzAdeNt9bIQK64kbYbl1hZarE31bI5FFjV2LEMx3FTF8LkRgpY+G2xIRbWFHDGuPvnY7OtLL6w3PJMhoFz5tE6CCPRtdoku1LWa2+0fJSE3CmYTbBeBExefoy7U9wG5VGYf3xwdqgeSet1LdJAOuMOO1seFEiQgbqiBUbU/Gu4kKROOaLHtE7IyMUogugWmeCqw35AxDX74sFm8Fhwy0hbZcQXlvZWJjYDk+Ga3HWKJ7CvTN/LjMFD80L0UEMdZdPAjc1cF2n8m4SMzuwFSK69sQxeizMDydY7TmQVPasJYfLXTQ3yVSTShijIkKVQbSMWe0doRwp1NPXImbjvif2U1yV9czfp8DrqrKnHa2XT/Qxqhw2XAS/5ChRaWPFKsvrfxTznTY6Pgiwrc3l6WgRfTcGNxKtIJR73XRXcAjPdAxQGDwsjJxA7UCWEKNBJ0skqHd4jzOpgwsfhru3Sfkg5peR9iDZ+CnNZNjMGsxNPhDij/39Qxc9HJLl7iLnlQJrbD6Uzz+w8hB0shrbG6JTssVHeCLfNd0Eu6gEK/ZEH0bCKYlBuuBqK0E1EcCRFp51YCoBYUogXr0fD6o7cMqlPeWoeS/li/y/DIx8zybvymD1SDyOfVCH5lxvgq5EUCkEkVjboOVKl1ZYqJsxVw0NjQ1YBc/Pd8OzOhI17LgXsDosXlyIvzLfrgSHsI6r+aYa/uJXrUEB0J8zS4H0mZVCqh1+ALsMsmvSdJ46XtPFYAa2pTzoab/auXKAFLkRSce0E4W+sMj2Fdbr6LMzrbxs5KJy8rS3ADfYyofLN6/9mjkn+raelOYqyZdml4giGVCqjPHTFIvnms5ND1Ra6CelHtbQ4Tn9BJNuyS4ruqbzu2EUXFAhnL6g=="}


### Flask
POST http://localhost:5000/pp/pp
Accept: application/json

{"a": 123}