name: Build Ubuntu Image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'ubuntu/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'ubuntu/**'
  workflow_dispatch :

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        # registry: # optional
        # Username used to log against the Docker registry
        username: leecq
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_TOKEN }} 
        # Specifies whether the given registry is ECR (auto, true or false)
        # ecr: # optional, default is auto
        # Log out from the Docker registry at the end of a job
        # logout: # optional, default is true
    
    - name: Build the Docker image
      run: |
        cd ubuntu
        sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

        tag="$(git log | head -n 1 | python3 -c 'a=input();print(a[7:13])')-$(date +%m%d-%H%m)"
        image_name=leecq/ubuntu
        docker build . --file Dockerfile --tag ${image_name}:"${tag}"
        docker tag ${image_name}:"${tag}" ${image_name}

        docker push ${image_name}
        docker push ${image_name}:"${tag}"
        
