name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        # registry: # optional
        # Username used to log against the Docker registry
        username: leecq
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_TOKEN }} 
        # Specifies whether the given registry is ECR (auto, true or false)
        # ecr: # optional, default is auto
        # Log out from the Docker registry at the end of a job
        # logout: # optional, default is true
    
    - name: Build the Docker image
      run: |
        sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        
        tag=$(date +%m%d-%H%m) 
        docker build . --file Dockerfile --tag leecq/host-service:"${tag}" --build-arg image_version=3.11
        docker tag host-service:"${tag}" leecq/host-service

        docker push leecq/host-service
        docker push leecq/host-service:"${tag}"
        
