name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: |
        tag=$(date +%s) 
        docker build . --file Dockerfile --tag host-service:"${tag}" --build-arg image_version=3.11
        docker tag host-service:"${tag}" host-service
        echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin 
        docker push host-service
        docker push host-service:"${tag}"
        
